In [ ]:
# library to work with
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Fortune500.csv')
#data

In [ ]:
df

,Rank,Title,Employees,Sector,Industry,Hqcity,Ceo,Ceo-title,Revenues,Revchange,Profits,Prftchange,Assets
0,1,Walmart,2300000,Retailing,General Merchandisers,Bentonville,C. Douglas McMillon,"President, Chief Executive Officer & Director",485873,0.8,13643.0,-7.2,198825
1,2,Berkshire Hathaway,367700,Financials,Insurance: Property and Casualty (Stock),Omaha,Warren E. Buffett,Chairman & Chief Executive Officer,223604,6.1,24074.0,0,620854
2,3,Apple,116000,Technology,"Computers, Office Equipment",Cupertino,Timothy D. Cook,Chief Executive Officer & Director,215639,-7.7,45687.0,-14.4,321686
3,4,Exxon Mobil,72700,Energy,Petroleum Refining,Irving,Darren W. Woods,Chairman & Chief Executive Officer,205004,-16.7,7840.0,-51.5,330314
4,5,McKesson,68000,Wholesalers,Wholesalers: Health Care,San Francisco,John H. Hammergren,"Chairman, President & Chief Executive Officer",192487,6.2,2258.0,53,56563
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Michaels Cos.,31000,Retailing,Specialty Retailers: Other,Irving,Carl S. Rubin,Chairman & Chief Executive Officer,5197,5.8,378.2,4.2,2148
496,497,Toll Brothers,4200,Engineering & Construction,Homebuilders,Horsham,Douglas C. Yearley Jr.,Chief Executive Officer & Director,5170,23.9,382.1,5.2,9737
497,498,Yahoo,8500,Technology,Internet Services and Retailing,Sunnyvale,Marissa A. Mayer,"President, Chief Executive Officer & Director",5169,4.0,-214.3,5.2,48083
498,499,Vistra Energy,4431,Energy,Energy,Dallas,Curtis A. Morgan,"President, Chief Executive Officer & Director",5164,4.0,-214.3,5.2,15167
499,500,ABM Industries,110000,Business Services,Diversified Outsourcing Services,New York,Scott B. Salmirs,"President, Chief Executive Officer & Director",5145,-2.8,57.2,-25,2281

In [ ]:
# first five rows
df.head()

,Rank,Title,Employees,Sector,Industry,Hqcity,Ceo,Ceo-title,Revenues,Revchange,Profits,Prftchange,Assets
0,1,Walmart,2300000,Retailing,General Merchandisers,Bentonville,C. Douglas McMillon,"President, Chief Executive Officer & Director",485873,0.8,13643.0,-7.2,198825
1,2,Berkshire Hathaway,367700,Financials,Insurance: Property and Casualty (Stock),Omaha,Warren E. Buffett,Chairman & Chief Executive Officer,223604,6.1,24074.0,0,620854
2,3,Apple,116000,Technology,"Computers, Office Equipment",Cupertino,Timothy D. Cook,Chief Executive Officer & Director,215639,-7.7,45687.0,-14.4,321686
3,4,Exxon Mobil,72700,Energy,Petroleum Refining,Irving,Darren W. Woods,Chairman & Chief Executive Officer,205004,-16.7,7840.0,-51.5,330314
4,5,McKesson,68000,Wholesalers,Wholesalers: Health Care,San Francisco,John H. Hammergren,"Chairman, President & Chief Executive Officer",192487,6.2,2258.0,53,56563

In [ ]:
# to view how long is your data set
df.shape

(500, 13)

In [ ]:
#information about the columns
#very important before working on dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rank        500 non-null    int64
 1   Title       500 non-null    object
 2   Employees   500 non-null    int64
 3   Sector      500 non-null    object
 4   Industry    500 non-null    object
 5   Hqcity      500 non-null    object
 6   Ceo         500 non-null    object
 7   Ceo-title   500 non-null    object
 8   Revenues    500 non-null    int64
 9   Revchange   500 non-null    float64
 10  Profits     500 non-null    float64
 11  Prftchange  500 non-null    object
 12  Assets      500 non-null    int64
dtypes: float64(2), int64(4), object(7)
memory usage: 50.9+ KB

In [ ]:
sub_df = df[['Rank','Title','Employees','Sector','Revenues','Profits']]

In [ ]:
sub_df.head()

   Rank               Title  Employees       Sector  Revenues  Profits
0     1             Walmart    2300000    Retailing    485873  13643.0
1     2  Berkshire Hathaway     367700   Financials    223604  24074.0
2     3               Apple     116000   Technology    215639  45687.0
3     4         Exxon Mobil      72700       Energy    205004   7840.0
4     5            McKesson      68000  Wholesalers    192487   2258.0

In [ ]:
sub_df.head(10)

,Rank,Title,Employees,Sector,Revenues,Profits
0,1,Walmart,2300000,Retailing,485873,13643.0
1,2,Berkshire Hathaway,367700,Financials,223604,24074.0
2,3,Apple,116000,Technology,215639,45687.0
3,4,Exxon Mobil,72700,Energy,205004,7840.0
4,5,McKesson,68000,Wholesalers,192487,2258.0
5,6,UnitedHealth Group,230000,Health Care,184840,7017.0
6,7,CVS Health,204000,Health Care,177526,5317.0
7,8,General Motors,225000,Motor Vehicles & Parts,166380,9427.0
8,9,AT&T,268540,Telecommunications,163786,12976.0
9,10,Ford Motor,201000,Motor Vehicles & Parts,151800,4596.0

In [ ]:
sub_df.describe()

             Rank     Employees       Revenues       Profits
count  500.000000  5.000000e+02     500.000000    500.000000
mean   250.492000  5.635013e+04   24111.748000   1779.479800
std    144.477366  1.234520e+05   38337.353337   3937.558721
min      1.000000  8.300000e+01    5145.000000  -6177.000000
25%    125.750000  1.190000e+04    7245.000000    235.725000
50%    250.500000  2.500000e+04   11384.000000    683.600000
75%    375.250000  5.682525e+04   22605.250000   1770.775000
max    500.000000  2.300000e+06  485873.000000  45687.000000

In [ ]:
# for indivisual
mean_rev = sub_df['Revenues'].mean()
mean_rev

24111.748

In [ ]:
print(mean_rev)

24111.748

In [ ]:
median_rev = sub_df['Revenues'].median()
median_rev

11384.0

In [ ]:
print(median_rev)

11384.0

In [ ]:
mode_rev = sub_df['Revenues'].mode()
mode_rev

0    9061
Name: Revenues, dtype: int64

In [ ]:
print(mode_rev)

0    9061
Name: Revenues, dtype: int64

In [ ]:
s = sub_df['Revenues'].min()
s

5145

In [ ]:
s1 = sub_df['Revenues'].max()
s1

485873

In [ ]:
range = s1-s
range

480728

In [ ]:
# for advance work
range2 = sub_df['Revenues'].max()-sub_df['Revenues'].min()
range2

480728

In [ ]:
sd=sub_df['Revenues'].std()
sd

38337.35333653324

In [ ]:
var=sub_df['Revenues'].var()
var

1469752660.8501961

In [ ]:
# IQR
# QUANTILE
# P75 = Q3 AND P25 = Q1

In [ ]:
q1=sub_df['Revenues'].quantile(0.25)
q1

7245.0

In [ ]:
q3=sub_df['Revenues'].quantile(0.75)
q3

22605.25

In [ ]:
# IQR=Q3-Q1
IQR=sub_df['Revenues'].quantile(0.75)-sub_df['Revenues'].quantile(0.25)
IQR

15360.25

In [ ]:
IQR2=q3-q1
IQR2

15360.25

In [ ]:
skew=sub_df['Revenues'].skew()
skew

5.480066970305041

In [ ]:
import seaborn as sns
skew=sub_df['Revenues'].skew()
skew

5.480066970305041

In [ ]:
# CALCULATE CV FOR THE REVENUES COLOUMN
# CV=(SD/MEAN)*100

In [ ]:
cv=sub_df['Profits'].std()/sub_df['Profits'].mean()*100
cv

221.2758313353473

In [ ]:
# cv2=sd/mean*100
# cv2

In [ ]:
# print("the cv revenues column is ",cv2,"%")

In [ ]:
# print("cv of profit column is ",cv,"%")

In [ ]:
# df_sample=sub_df.sample(frac=0.70,random_state=0)
# # df_sample.head()
# mean2=df_sample['Revenues'].mean()
# print(mean2)

In [ ]:
# df_sample=sub_df.sample(frac=0.70,random_state=1)
# # df_sample.head()
# mean3=df_sample['Revenues'].mean()
# print(mean3)

In [ ]:
upper_limit= sub_df["Revenues"].quantile(0.75)+1.5*IQR
upper_limit

45645.625

In [ ]:
lower_limit= sub_df["Revenues"].quantile(0.25)-1.5*IQR
lower_limit

-15795.375

In [ ]:
# outliers are those values which reside outside of the lower and upper limits boundries
outliers = sub_df[(sub_df['Revenues']>upper_limit) |
                  (sub_df['Revenues']<lower_limit)]
print("Outliers Rows")
print(outliers)

Outliers Rows
    Rank                       Title  Employees          Sector  Revenues  \
0      1                     Walmart    2300000       Retailing    485873
1      2          Berkshire Hathaway     367700      Financials    223604
2      3                       Apple     116000      Technology    215639
3      4                 Exxon Mobil      72700          Energy    205004
4      5                    McKesson      68000     Wholesalers    192487
..   ...                         ...        ...             ...       ...
57    58                       FedEx     335767  Transportation     50365
58    59  Hewlett Packard Enterprise     195000      Technology     50123
59    60               Cisco Systems      73700      Technology     49247
60    61                          HP      49000      Technology     48238
61    62                Dow Chemical      56000       Chemicals     48158

    Profits
0   13643.0
1   24074.0
2   45687.0
3    7840.0
4    2258.0
..      ...
57   1820.0
58   3161.0
59  10739.0
60   2496.0
61   4318.0

[62 rows x 6 columns]